version: '3'

services:
  sauron-cln:
    build: .
    image: nostr-relay:latest
    container_name: nostr-relay
    hostname: nostr-relay
    env_file: .env
    init: true
    networks:
      - net
    ports:
      - 8080:8080
    restart: unless-stopped
    tty: true
    volumes:
      - ./config/config.toml:/usr/src/app/config.toml:ro
      - ./data:/usr/src/app/db:rw
      - ./home:/root/home:rw

networks:
  net:
    name: 'nostr'
